#!/usr/bin/env bash
# Configure or installs a new Nginx server to redirect to another page

REDIR="/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
SRC="/etc/nginx/sites-available/default"
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown "$USER":"$USER" /var/www/html/index.html
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "/listen 80 default_server;$REDIR" $SRC
sudo service nginx restart
