#!/usr/bin/env bash
#a bash script to configure web-02 to be identical to web-01
apt-get -y update
apt-get -y install nginx
ufw allow  'Nginx HTTP' #on port 80
echo "Hello World!" >/var/www/html/index.nginx-debian.html
sed -i '41i rewrite ^/redirect_me https://www.nginx.com/ permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sed -i "52i add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart
