#!/usr/bin/env bash
# Loops 10 times, prints "Best School" everytime expect from:
# 4th loop iteration: Prints "bad luck"
# 8th loop iteration: Prints "good luck"

i="0"
while [ $i -lt 10 ]
do
if [ $i -eq 3 ];
then
    echo "bad luck"
elif [ $i -eq 7 ];
then
    echo "good luck"
else
    echo "Best School"
fi
i=$((i+1))
done
